#!/usr/bin/env bash

PYTHON="python3.10"

# Fail if anything fails
set -e

script_dir=$(dirname "$(readlink -f "$0")")
venv_dir="$script_dir/venv"

#Activate virtual environment
if [[ -z "$VIRTUAL_ENV" ]]; then
    (
        cd $script_dir
        make check-venv
    )
    . "$venv_dir/bin/activate"
fi

# Run
python "$script_dir/src/build.py" "$@"
exit $?
