#!/usr/bin/env python3

import argparse
import errno
import glob
import json
import os.path
import shutil
import subprocess
import sys

BUILDDATADIR = os.path.join(os.path.abspath(os.path.dirname(__file__)), '.builddata')

# [type, required, default, values]
VALID_INFO = {
    'projectname': [str, True],
    'builddir': [str, True],
    'flags': [str, False, ''],
    'libraries': [[str], False, []],
    'targets': [[dict], True],
    'include_dirs': [[str], False, []],
    'copy': [[str], False, []],
}
VALID_TARGETS = {
    'name': [str, True],
    'type': [str, False, 'executable', ['executable', 'sharedlib', 'staticlib']],
    'srcs': [[str], True],
    'flags': [str, False, ''],
    'libraries': [[str], False, []],
    'include_dirs': [[str], False, []],
    'install_to': [[str], False, []],
    'install_includes': [[str], False, []],
}
VALID_LIBRARIES = {
    'find_package': [[str], False, []],
    'pkg_check':    [[str], False, []],
    'include_dirs': [[str], False, []],
    'link_dirs':    [[str], False, []],
    'link_libs':    [[str], True],
}

CMAKEFILES = ['CMakeCache.txt', 'CMakeFiles', 'cmake_install.cmake', 'Makefile']

LIBRARIES = {}


def load_libraries_dir(directory):
    for libfilename in glob.glob(os.path.join(directory, '*')):
        libraries = load_json(libfilename)
        for libname, libdata in libraries.items():
            validate('library ' + libname, libdata, VALID_LIBRARIES)
            LIBRARIES[libname] = libdata


def load_libraries(info):
    librarydir = os.path.join(BUILDDATADIR, 'libs')
    load_libraries_dir(librarydir)
    locallibs = info.get('locallibs')
    if locallibs:
        load_libraries_dir(locallibs)
    librarynames = list(LIBRARIES.keys())
    VALID_INFO['libraries'].append(librarynames)
    VALID_TARGETS['libraries'].append(librarynames)


def main():
    args = parse_args()
    if args.listtemplates:
        print('Available templates: ' + ', '.join(all_templates()))
        return
    if args.projectname:
        copy_template(args.file, args.projectname, args.template)
    data = read_info(args.file)
    data['no_cmake'] = args.nocmake
    data['no_make'] = args.nomake
    data['run_cmake'] = False
    info = data['info']
    load_libraries(info)
    validate_info(info)
    is_git = is_git_repo()
    if not is_git and not args.nogit:
        init_git()
        is_git = True
    builddir = info['builddir']
    os.makedirs(builddir, exist_ok=True)
    check_source_files(data)
    if data['need_init']:
        generate_cmake(info, 'CMakeLists.txt')
        if is_git:
            generate_gitignore(info)
        data['run_cmake'] = True
    if data['run_cmake'] and not data['no_cmake']:
        run_cmake(builddir)
    if not data['no_make']:
        run_make(builddir, args.sudo, args.make_args)


def parse_args():
    desc = 'Easy to use wrapper script around cmake and make'
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument(
        '-f', '--file', action='store',
        help='Use FILE as the build file')
    parser.add_argument(
        '-i', '--init', action='store', dest='projectname',
        help='Initialize a new project build. This generates a new build.info file.')
    parser.add_argument(
        '-t', '--template', action='store',
        help='With -i/--init, use a template for initialization')
    parser.add_argument(
        '-T', '--listtemplates', action='store_true',
        help='List all available templates')
    parser.add_argument(
        '-c', '--nocmake', action='store_true',
        help='Don\'t run cmake')
    parser.add_argument(
        '-m', '--nomake', action='store_true',
        help='Don\'t run make')
    parser.add_argument(
        '-g', '--nogit', action='store_true',
        help='Don\'t create a git repository (with -i/--init)')
    parser.add_argument(
        '-s', '--sudo', action='store_true',
        help='Run make with sudo')
    parser.add_argument(
        'make_args', action='store', nargs='*',
        help='Pass argument to make')
    args = parser.parse_args()

    if args.file is None:
        args.file = 'build.info'
    if args.projectname and not args.template:
        args.template = 'default'

    return args


def is_git_repo():
    command = ['git', 'rev-parse', '--git-dir']
    rc = subprocess.call(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return rc == 0


def load_json(filename):
    try:
        with open(filename, 'r') as f:
            return json.load(f)
    except ValueError as e:
        print('Failed to load data from ' + filename + ': ' + str(e), file=sys.stderr)
        sys.exit(1)


def copy_file(file, dest):
    try:
        shutil.copytree(file, dest)
    except OSError as e:
        if e.errno == errno.ENOTDIR:
            shutil.copy(file, dest)
        else:
            raise


def all_templates():
    all_template_dir = os.path.join(BUILDDATADIR, 'templates')
    return sorted([d for d in os.listdir(all_template_dir)
                   if os.path.isdir(os.path.join(all_template_dir, d))])


def copy_template(file, projectname, template):
    all_template_dir = os.path.join(BUILDDATADIR, 'templates')
    templatedir = os.path.join(all_template_dir, template)
    if not os.path.isdir(templatedir):
        print('ERROR: Invalid template \'' + template + '\'. Valid templates: ' +
              ', '.join(all_templates()), file=sys.stderr)
        sys.exit(1)
    buildinfo = os.path.join(templatedir, 'build.info')
    if not os.path.isfile(buildinfo):
        print('ERROR: Invalid template \'' + template + '\'. Missing build.info',
              file=sys.stderr)
        sys.exit(1)
    with open(buildinfo, 'r') as f:
        buildinfocontents = f.read()
    buildinfocontents = buildinfocontents.replace('${project}', projectname)
    with open(file, 'w') as f:
        print(buildinfocontents, file=f)
    for filename in [f for f in os.listdir(templatedir) if f != 'build.info']:
        src = os.path.join(templatedir, filename)
        copy_file(src, filename)


def move_cmake_files(srcdir, destdir):
    for file in CMAKEFILES:
        src = os.path.join(srcdir, file)
        dest = os.path.join(destdir, file)
        try:
            shutil.move(src, dest)
        except FileNotFoundError:
            pass


def run_command(command):
    print('Running ' + ' '.join(command))
    return subprocess.call(command)


def init_git():
    command = ['git', 'init']
    run_command(command)


def generate_gitignore(info):
    print('Generating .gitignore')
    gitignore = [
        '#-- Generated by build --#',
        '# Build dir',
        '/build.dir',
        '',
        '# Vim swap files',
        '*.swp',
        '*.swo',
        '',
        '# Object files',
        '*.o',
        '',
        '# Libraries',
        '*.a',
        '*.so',
    ]
    executables = []
    has_install = False
    for target in info['targets']:
        if target['type'] == 'executable':
            executables.append(target['name'])
        if target['install_to']:
            has_install = True
    if has_install:
        gitignore.append('')
        gitignore.append('# Install manifest')
        gitignore.append('/install_manifest.txt')
    if executables:
        gitignore.append('')
        gitignore.append('# Executables')
        gitignore.append('\n'.join(['/' + exe for exe in executables]))

    endline = '#-- End generated by build --#'
    gitignore.append('')
    gitignore.append(endline)

    extra = []
    if os.path.isfile('.gitignore'):
        with open('.gitignore', 'r') as f:
            extra = f.read().split('\n')
            if endline in extra:
                extra = extra[extra.index(endline)+1:-1]

    with open('.gitignore', 'w') as f:
        print('\n'.join(gitignore+extra), file=f)


def run_cmake(builddir):
    move_cmake_files(builddir, '.')
    try:
        command = ['cmake', '.']
        run_command(command)
    finally:
        move_cmake_files('.', builddir)


def run_make(builddir, sudo, args):
    move_cmake_files(builddir, '.')
    try:
        command = ['sudo'] if sudo else []
        command += ['make'] + args
        run_command(command)
    finally:
        move_cmake_files('.', builddir)


def validate(name, data, valid):
    missingRequired = []
    invalidTypes = []
    invalidValues = []
    for key, value in valid.items():
        valueType = value[0]
        if type(valueType) is list:
            listType = valueType[0]
            valueType = list
        required = value[1]
        default = value[2] if len(value) > 2 else None
        values = value[3] if len(value) > 3 else None
        if key in data:
            val = data[key]
            if isinstance(val, valueType):
                if valueType is list:
                    for elem in val:
                        if not isinstance(elem, listType):
                            invalidTypes.append([key, [listType], type(elem)])
                if values is not None:
                    if isinstance(val, list):
                        vals = val
                    else:
                        vals = [val]
                    for val in vals:
                        if val not in values:
                            invalidValues.append([key, values, val])
            else:
                invalidTypes.append([key, valueType, type(val)])
        elif required:
            missingRequired.append(key)
        else:
            data[key] = default
    if missingRequired or invalidTypes or invalidValues:
        print('ERROR: Invalid ' + name + ':')
        if missingRequired:
            print('    Missing required values: ' + ', '.join(missingRequired))
        for key, expected, actual in invalidTypes:
            if isinstance(expected, list):
                message = 'Invalid type in \'' + key + '\' list: '
                expected = expected[0]
            else:
                message = 'Invalid type for \'' + key + '\': '
            print('    ' + message +
                  'expected: ' + str(expected) + ', actual: ' + str(actual))
        for key, expected, actual in invalidValues:
            print('    Invalid value for \'' + key + '\': ' +
                  'expected one of [' + ', '.join(expected) + '], ' +
                  'actual: ' + actual)
        sys.exit(1)


def validate_info(info):
    validate('build info file', info, VALID_INFO)
    for count, target in enumerate(info['targets']):
        validate('target(' + str(count+1) + ')', target, VALID_TARGETS)


def read_info(filename):
    data = {}
    if os.path.isfile(filename):
        data['info'] = load_json(filename)
    else:
        print('ERROR: build info file \'' + filename + '\' does not exist. ' +
              'Run \'build --help\' for help',
              file=sys.stderr)
        sys.exit(1)

    build_dir = data['info'].get('builddir')
    if build_dir:
        cmakefile = 'CMakeLists.txt'
        if os.path.isfile(cmakefile):
            info_ts = os.path.getmtime(filename)
            cmake_ts = os.path.getmtime(cmakefile)
            data['need_init'] = (info_ts > cmake_ts)
        else:
            data['need_init'] = True

    return data


def get_sources(pattern):
    if '*' not in pattern:
        return [pattern]
    filedir = os.path.dirname(pattern)
    filename = os.path.basename(pattern)
    command = ['find', filedir, '-name', filename]
    proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    stdout, stderr = proc.communicate()
    return list(filter(None, stdout.decode('utf-8').split('\n')))


def check_source_files(data):
    info = data['info']
    srcdir = os.path.join(info['builddir'], 'srcs')
    os.makedirs(srcdir, exist_ok=True)
    all_srcs = {}
    for srcfile in glob.glob(os.path.join(srcdir, '*')):
        with open(srcfile, 'r') as f:
            target = os.path.basename(srcfile)
            all_srcs[target] = list(filter(None, f.read().split('\n')))
            os.remove(srcfile)
    for target in info['targets']:
        name = target['name']
        srcs = [src for srcs in target['srcs'] for src in get_sources(srcs)]
        if not srcs:
            data['no_cmake'] = True
            data['no_make'] = True
        if name not in all_srcs or all_srcs[name] != srcs:
            data['run_cmake'] = True
        with open(os.path.join(srcdir, name), 'w') as f:
            print('\n'.join(srcs), file=f)


def unique_list(lst):
    seen = set()
    return [elem for elem in lst if not (elem in seen or seen.add(elem))]


def generate_cmake(info, filename):
    cmake_data = [
        'cmake_minimum_required(VERSION 2.8 FATAL_ERROR)',
        '',
        'project(' + info['projectname'] + ')',
    ]

    print('Generating CMakeLists.txt')

    base_libraries = info['libraries']
    all_libraries = base_libraries.copy()
    target_libraries = {}
    for target in info['targets']:
        target_libs = target['libraries']
        all_libraries += target_libs
        libs = base_libraries + target_libs
        target_libraries[target['name']] = [LIBRARIES[lib] for lib in libs]
    lib_data = [LIBRARIES[lib] for lib in unique_list(all_libraries)]

    find_packs = sum([lib['find_package'] for lib in lib_data], [])
    pkg_checks = sum([lib['pkg_check'] for lib in lib_data], [])
    link_dirs = sum([lib['link_dirs'] for lib in lib_data], [])

    if find_packs:
        cmake_data.append('')
        for pack in find_packs:
            cmake_data.append('find_package(' + pack + ')')

    if pkg_checks:
        cmake_data.append('')
        cmake_data.append('INCLUDE(FindPkgConfig)')
        cmake_data.append('')
        for pkg_check in pkg_checks:
            cmake_data.append('pkg_check_modules(' + pkg_check + ')')

    if link_dirs:
        cmake_data.append('link_directories(' + ' '.join(link_dirs) + ')')

    install_libs = []

    install_types = set()

    for target in info['targets']:
        name = target['name']
        libs = target_libraries[name]
        cmake_data.append('')
        files_var = 'SRC_FILES_' + name
        cmake_data.append(
            'file(GLOB_RECURSE ' + files_var + ' ' + ' '.join(target['srcs']) + ')')
        type_dict = {
            'executable': 'add_executable(' + name + ' ${' + files_var + '})',
            'sharedlib': 'add_library(' + name + ' SHARED ${' + files_var + '})',
            'staticlib': 'add_library(' + name + ' STATIC ${' + files_var + '})'
        }
        cmake_data.append(type_dict[target['type']])
        flags = (info['flags'] + ' ' + target['flags']).strip()
        if flags:
            options = name + ' PRIVATE ' + flags
            cmake_data.append('target_compile_options(' + options + ')')

        include_dirs = sum([lib['include_dirs'] for lib in libs], [])
        include_dirs += info['include_dirs'] + target['include_dirs']
        if include_dirs:
            dirs = ' '.join(include_dirs)
            cmake_data.append(
                'target_include_directories(' + name + ' PRIVATE ' + dirs + ')')

        link_libs = sum([lib['link_libs'] for lib in libs], [])
        if link_libs:
            links = ' '.join(link_libs)
            cmake_data.append('target_link_libraries(' + name + ' ' + links + ')')

    include_files = []
    include_patterns = []

    install_types = {
        'executable': 'RUNTIME',
        'sharedlib': 'LIBRARY',
        'staticlib': 'ARCHIVE'
    }

    cmake_data.append('')

    for target in info['targets']:
        name = target['name']
        install_type = install_types[target['type']]
        for dest in target['install_to']:
            cmake_data.append('install(TARGETS ' + name + ' ' + install_type +
                              ' DESTINATION ' + dest + ')')

        for include in target['install_includes']:
            if '*' in include:
                srcdir = os.path.dirname(include)
                if srcdir[-1] != '/':
                    srcdir += '/'
                pattern = os.path.basename(include)
                include_patterns.append([srcdir, pattern])
            else:
                include_files.append(include)
        if target['type'] in ('sharedlib', 'staticlib') and target.get('install'):
            install_libs.append(name)
            install_types.add(target['type'])

    if install_libs:
        cmake_data.append('install(TARGETS ' + ' '.join(install_libs) +
                          'ARCHIVE DESTINATION lib)')

    if include_files:
        files = ' '.join(include_files)
        cmake_data.append('install(FILES ' + files + ' DESTINATION include)')
    for include_pattern in include_patterns:
        srcdir = include_pattern[0]
        pattern = include_pattern[1]
        cmake_data.append('install(DIRECTORY ' + srcdir +
                          ' DESTINATION include FILES_MATCHING PATTERN "' +
                          pattern + '")')

    for copy in info['copy']:
        cmake_data.append(copy)

    move_cmake_files('.', info['builddir'])
    try:
        with open(filename, 'w') as f:
            print('\n'.join(cmake_data), file=f)
    finally:
        move_cmake_files(info['builddir'], '.')


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('build: Interrupt')
