[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true

[tool.mypy]
python_version = "3.10"
strict = true

[tool.pylint]
disable = [
    'missing-class-docstring',
    'missing-function-docstring',
    'unused-argument',
]
